import type { Metadata } from 'next'
import { Inter, Rubik } from "next/font/google";
import './globals.css'



const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portefeuilles - EIP",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
